### ISSUE TITLE
[Company Profile]: Typo in Website spelling. It should be Website and not Web Site.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#10]
Typo in Website spelling. It should be Website and not Web Site.

![cp-08](https://user-images.githubusercontent.com/31267260/29956695-4713fb9e-8f06-11e7-94dd-be93424c1352.jpg)

**Comment by prashantk0270** [comment]
done & updated

**Comment by bhavinshah09** [comment]
The issue is fixed and verified.
