### ISSUE TITLE
[Role]: Typo in Role listing page, spelling of 'Configure' is incorrect.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#131]
Actual Result : Typo in Role listing page, spelling of 'Configure' is incorrect.

Expected Result : Spelling of 'Configure' should be corrected.

![rol-11](https://user-images.githubusercontent.com/31267260/30584039-30e046d6-9d46-11e7-9e72-d082164ee32b.jpg)

**Comment by jariwbh** [comment]
done

**Comment by bhavinshah09** [comment]
The issue is Fixed and verified. Now Configure Permission text shall not be displayed instead icon will be displayed.
