### ISSUE TITLE
[Role]: System duplicates the entries while updating details in 'Edit' mode.***

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#142]
Actual Result : System duplicates the entries while updating details in 'Edit' mode.

Expected Result : System should update the entry showing Update success message in 'Edit' mode.

Steps to Reproduce : 

1. Go to http://52.163.113.185:3001/#/login
2. Login using admin username and password
3. Navigate to Role under Users and Role.
4. Select a particular record.
5. Click on 'Edit' icon.
6. Click on 'Save'.
-> Observe the issue.

![rol-12](https://user-images.githubusercontent.com/31267260/30681834-c76e0d84-9ec4-11e7-9e7b-d201b01daced.jpg)

**Comment by jariwbh** [comment]
done

**Comment by bhavinshah09** [comment]
The issue is Fixed and verified.
