### ISSUE TITLE
[Company Profile]: Mandatory fields are not marked with asterisk '*'

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#18]
Actual Result : Mandatory fields are not marked with asterisk '*'

Expected Result : Mandatory fields should be marked with asterisk '*'

Steps to Reproduce : 

1. Go to http://52.163.113.185:3001/#/login
2. Login using admin username and password
3. Navigate to Company Profile page under Organization
-> Observe that the mandatory fields are not marked with asterisk '*'.

![cp-16](https://user-images.githubusercontent.com/31267260/29967190-0ed29e16-8f33-11e7-8183-27cecda4fe35.jpg)

**Comment by prashantk0270** [comment]
done

**Comment by bhavinshah09** [comment]
The issue is fixed as per expected result and verified.
