### ISSUE TITLE
[Company Profile]: System shows error message upon saving/updating the info.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#2]
Actual Result : System shows 'Organization detail not valid' error upon saving the info.

Expected Result : System should save the details successfully showing save success message.

Steps to Reproduce :
 
1. Go to http://52.163.113.185:3001/#/login
2. Login using admin username and password
3. Navigate to Company Profile page under Organization
4. Click on Edit Profile
5. Modify any detail and click on 'Save changes'.
-> Observe that the system shows 'Organization detail not valid' error.
![cp-01](https://user-images.githubusercontent.com/31267260/29955068-4945f54a-8efa-11e7-8e26-4d81fdb47e10.jpg)

**Comment by prashantk0270** [comment]
Solved & Updated

**Comment by bhavinshah09** [comment]
The issue is fixed as per expected result hence verified.
