### ISSUE TITLE
[Lookup]: Font size consistency issue.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#22]
Actual Result : Text font size is different for different labels & text boxes.

Expected Result : Text font size should be consistent across all the field labels & text boxes.

![lu-03](https://user-images.githubusercontent.com/31267260/30770883-4799e362-a059-11e7-9785-7a9e26f8a369.jpg)

**Comment by kalpesh2017** [comment]
Done

**Comment by bhavinshah09** [comment]
The issue is Fixed and verified.
