### ISSUE TITLE
[Lookup]: Typo in select Lookup drop down. Payment Methods is mentioned as a single word.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#24]
Actual Result : Typo in select Lookup drop down. Payment Methods is mentioned as a single word.

Expected Result : Payment Methods is two separate words so correct it to PAYMENT METHODS instead of PaymentMethods.

![lu-05](https://user-images.githubusercontent.com/31267260/30013939-25af6980-9167-11e7-8c7d-42a04f6d3c81.jpg)

**Comment by prashantk0270** [comment]
fixed & updated

**Comment by bhavinshah09** [comment]
The issue is fixed as per expected result and verified.
