### ISSUE TITLE
[Membership Plan]: In responsive view, the design breaks.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#26]
Actual Result : In responsive view, the design breaks.

Expected Result : Design should not break upon resizing the window and responsive view. Alignment of text for each field should be proper.

![mbsr-01](https://user-images.githubusercontent.com/31267260/30016563-3f0f60ea-9173-11e7-902f-e6bbfbdd5f3b.jpg)

**Comment by kalpesh2017** [comment]
Done

**Comment by bhavinshah09** [comment]
The issue is Fixed and Verified.
