### ISSUE TITLE
[Membership Plan]: Make the alignment for label in centre vertically with respect to drop down.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#29]
Make the alignment for label in centre vertically with respect to drop down.

![mbsr-04](https://user-images.githubusercontent.com/31267260/30021435-fe08d4a2-9184-11e7-8054-c2264adef730.jpg)

**Comment by kalpesh2017** [comment]
Done

**Comment by bhavinshah09** [comment]
The issue is Fixed and verified.
