### ISSUE TITLE
[Membership Plan]: Revise the delete confirmation message to "Are you sure you want to delete ?"

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#30]
Revise the delete confirmation message to "Are you sure you want to delete ?"

Note : Revise the message for all the delete buttons across the site.

![mbsr-05](https://user-images.githubusercontent.com/31267260/30021695-dfd45d3e-9185-11e7-8135-4b0dd7dafe28.jpg)

**Comment by prashantk0270** [comment]
done

**Comment by prashantk0270** [comment]
done & updated

**Comment by bhavinshah09** [comment]
The issue is Fixed and Verified.
