### ISSUE TITLE
[Membership Plan > Payment Terms]: User is allowed to select same payment term more than once.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#33]
Actual Result : User is allowed to select same payment term more than once.

Expected Result : User should not be allowed to select same payment term more than once.

Steps to Reproduce : 

1. Go to http://52.163.113.185:3001/#/login
2. Login using admin username and password
3. Navigate to Membership Plan under Members
4. Enter General tab details and save it.
5. Select the record and click on 'Edit'.
6. Navigate to Payment Terms tab.
7. Enter details for one payment term and save it.
8. Again enter the details for same payment term and save it.
-> Observe that the system saves the duplicate details successfully.

![mbsr-08](https://user-images.githubusercontent.com/31267260/30024728-c49ba362-9192-11e7-8a88-f432e4063cb4.jpg)

**Comment by prashantk0270** [comment]
done & updated

**Comment by bhavinshah09** [comment]
The issue is Fixed and verified.
