### ISSUE TITLE
[Membership Plan]: Alignment of certain fields is not proper in responsive view.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#35]
Actual Result : Alignment of certain fields is not proper in responsive view.

Expected Result : Alignment of all the fields should be proper in responsive view.
![mbsr-10](https://user-images.githubusercontent.com/31267260/30094668-3af201e2-92eb-11e7-8cfb-c7b063d64119.jpg)

**Comment by kalpesh2017** [comment]
Done

**Comment by bhavinshah09** [comment]
The issue is Fixed and Verified. Due to the structure and theme control the alignment shall break when viewed in a particular dimension.
