### ISSUE TITLE
[Membership Plan > Payment Terms]: In responsive view, drop down values are not getting displayed.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#36]
Actual Result :  In responsive view, drop down values are not getting displayed.

Expected Result : In responsive view, drop down values should be displayed properly.

![mbsr-11](https://user-images.githubusercontent.com/31267260/30094795-0cf348ae-92ec-11e7-8e08-4eba3247e0bf.jpg)

**Comment by kalpesh2017** [comment]
I have done changes, decreased the padding and it view as per occupying space.

**Comment by bhavinshah09** [comment]
The issue is fixed to a certain limit, upon resizing the window to a particular dimension the value in the combos will not be displayed completely.
