### ISSUE TITLE
[Membership Plan > Payment Terms]: Design is disturbing in responsive view (iPAD).

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#37]
Actual Result : Design is disturbing in responsive view.

Expected Result : Design should not break with fields and value/text boxes at proper alignment in responsive view.

![mbsr-12](https://user-images.githubusercontent.com/31267260/30094879-a52057ac-92ec-11e7-8389-c6d1bf5bd2ce.jpg)

**Comment by kalpesh2017** [comment]
Done

**Comment by bhavinshah09** [comment]
The issue is Fixed and verified.
