### ISSUE TITLE
[Membership Plan]: Hovering effect is not present on 'View More' link. Text color is also different.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#41]
Actual Result : Hovering effect is not present on 'View More' link. Text color is also different.

Expected Result : Make the text color for 'View More' link as per other links/navigation. Provide hovering effect as per other links (Eg. links at footer) .

Steps to Reproduce : 

1. Go to http://52.163.113.185:3001/#/login
2. Login using admin username and password
3. Navigate to Membership Plan under Members
4. Check the View More link.
-> Observe that the text color is different and hovering effect is also not present.

![mbsr-16](https://user-images.githubusercontent.com/31267260/30096511-662202c6-92f6-11e7-9203-48f4f6faee16.jpg)

**Comment by kalpesh2017** [comment]
Done

**Comment by bhavinshah09** [comment]
The issue is fixed and verified.
