### ISSUE TITLE
[Membership Plan]: Placeholder text is not visible completely.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#42]
Actual Result : Placeholder text is not visible completely.

Expected Result : Make the text size of placeholder smaller overall.

![mbsr-17](https://user-images.githubusercontent.com/31267260/30098417-81e1964e-92ff-11e7-8eb0-67e124d77845.jpg)

**Comment by kalpesh2017** [comment]
Done

**Comment by bhavinshah09** [comment]
The issue is Fixed and verified.

**Comment by kalpesh2017** [comment]
Done, The font size is same and for placeholder has less opacity it will remain same.
