### ISSUE TITLE
[Members]: Date selection should be a hand pointer instead of text pointer from calendar, upon selecting a date should accept the value and close the date picker.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#52]
Date selection should be a hand pointer instead of text pointer from calendar, upon selecting a date should accept the value and close the date picker.

![mem-09](https://user-images.githubusercontent.com/31267260/30107002-090383a6-931b-11e7-95e8-8e66fba9088b.jpg)

**Comment by kalpesh2017** [comment]
Please check with demo there is hover effect and cursor pointer is there, let me know when you implement, that time I can help you for color changes.

**Comment by bhavinshah09** [comment]
The issue is Fixed and verified.
