### ISSUE TITLE
[Users]: Design of the form is not appearing good. Header is cutting and going out of frame, no margin on right side, first word is not capitalized.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#56]
Actual Result : Design of the form is not appearing good. Header is cutting and going out of frame, no margin on right side, first word is not capitalized.

Expected Result : Design of the form should be appearing good. Header should not cut and get out of frame, provide some margin on right side, first word should be capitalized.

![usr-02](https://user-images.githubusercontent.com/31267260/30111642-1d227a66-932c-11e7-94ad-4752b9131841.jpg)

**Comment by kalpesh2017** [comment]
Spacing changes done but text click to capitalize and need to change the Basic Information heading to have different just bit bigger text

**Comment by bhavinshah09** [comment]
The issue is Fixed to certain extent and verified.
