### ISSUE TITLE
[Users]: Text size for 'Show' and 'Search' is not uniform as per other field labels and text boxes.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#59]
Actual Result : Text size for 'Show' and 'Search' is not uniform as per other field labels and text boxes.

Expected Result : Text size for 'Show' and 'Search' should be uniform as per other field labels and text boxes.

![usr-05](https://user-images.githubusercontent.com/31267260/30146096-a2e222c8-93b3-11e7-812d-702d7e41563a.jpg)

**Comment by kalpesh2017** [comment]
Font size will stay same but proper alignment done

**Comment by bhavinshah09** [comment]
The issue is Fixed as per expected result and verified.
