### ISSUE TITLE
[Users]: Add success message is grammatically incorrect.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#60]
Actual Result : Add success message is grammatically incorrect.

Expected Result : Revise the message to 'User has been added successfully'.

![usr-06](https://user-images.githubusercontent.com/31267260/30146225-78b17084-93b4-11e7-8ab5-330d6ab7c3ad.jpg)

**Comment by kalpesh2017** [comment]
Done and other these kind of alert also changed.

**Comment by bhavinshah09** [comment]
The issue is Fixed as per expected result and verified.
