### ISSUE TITLE
[Membership Plan]: Delete icon is different on listing page and on Payment Terms page.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#75]
Actual Result : Delete icon is different on listing page and on Payment Terms page.

Expected Result : Delete icon should be consistent on listing page and on Payment Terms page. Make it consistent throughout the site.

Steps to Reproduce : 

1. Go to http://52.163.113.185:3001/#/login
2. Login using admin username and password
3. Navigate to Membership Plan under Members
4. Mouse hover on the main image and check the delete icon.
-> Observe that the delete icon is of cross mark 'X'.
5. Navigate to Payment Terms page.
-> Observe that the delete icon is of trash bin.

![mbsr-21 1](https://user-images.githubusercontent.com/31267260/30162219-8fefbe76-93f1-11e7-9a01-bd10b6f7eda9.jpg)
![mbsr-21 2](https://user-images.githubusercontent.com/31267260/30162218-8feb7668-93f1-11e7-8243-81316c1256b2.jpg)

**Comment by prashantk0270** [comment]
done & updated

**Comment by bhavinshah09** [comment]
The issue is Fixed as per expected result and verified.
