### ISSUE TITLE
[Payment Setting > General]: System accepts invalid Email ID.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#79]
Actual Result : System accepts invalid Email ID.

Expected Result : Proper validation message should be displayed if user enter invalid Email ID.

![ps-02](https://user-images.githubusercontent.com/31267260/30237017-f1e0f208-9545-11e7-9dc4-8b5c842794ab.jpg)

**Comment by prashantk0270** [comment]
done & updated

**Comment by bhavinshah09** [comment]
The issue is Fixed and verified.
