### ISSUE TITLE
[Company Profile]: Fields arrangement is not proper.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#8]
Fields arrangement is not proper.
![cp-06](https://user-images.githubusercontent.com/31267260/29956468-f94b97ce-8f04-11e7-974b-821a12d329b1.jpg)

**Comment by prashantk0270** [comment]
done & updated

**Comment by bhavinshah09** [comment]
The issue is fixed as per expected result and verified.
