### ISSUE TITLE
[Payment Setting > General]: Mandatory field mark * is not present against required field. Proper validation message is not displayed for required fields.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#80]
Actual Result : Mandatory field mark * is not present against required field. Proper validation message is not displayed for required fields.

Expected Result : Mandatory field mark * should be present against required field. Proper validation message should be displayed for required fields if user leaves it blank.

![ps-03](https://user-images.githubusercontent.com/31267260/30237037-9352f10e-9546-11e7-952b-3ad4ba3b0400.jpg)

**Comment by prashantk0270** [comment]
done & updated

**Comment by bhavinshah09** [comment]
The issue is Fixed as per expected result and verified.
