### ISSUE TITLE
[Payment Setting > General]: Provide 'Cancel' button next to 'Save' button at the end of the form.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#82]
Provide 'Cancel' button next to 'Save' button at the end of the form.

![ps-05](https://user-images.githubusercontent.com/31267260/30237098-1a9f68ee-9548-11e7-9327-f51770abc64b.jpg)

**Comment by prashantk0270** [comment]
done & updated

**Comment by bhavinshah09** [comment]
The issue is Fixed and verified.
