### ISSUE TITLE
[Payment Setting > Payment Item]: There is no space between Payment and Item in placeholder text.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#83]
Actual Result : There is no space between Payment and Item in placeholder text.

Expected Result : Provide one character space between Payment and Item in placeholder text.

![ps-06](https://user-images.githubusercontent.com/31267260/30237162-c4e4104c-9549-11e7-86f5-44d9c6a70527.jpg)

**Comment by kalpesh2017** [comment]
Done

**Comment by bhavinshah09** [comment]
The issue is fixed and verified.

**Comment by kalpesh2017** [comment]
Done
