### ISSUE TITLE
[Payment Setting > Payment Item]: Align left the content for Name and Description columns.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#86]
Align left the content for Name and Description columns.

![ps-09](https://user-images.githubusercontent.com/31267260/30237259-d0895e96-954b-11e7-882f-64ebee0acfd1.jpg)

**Comment by kalpesh2017** [comment]
Done

**Comment by kalpesh2017** [comment]
Done

**Comment by bhavinshah09** [comment]
The issue is fixed and verified.
