### ISSUE TITLE
[Payment Setting > Tax]: Entering decimal point value in Amount field highlight field label in red color.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#87]
Actual Result : Entering decimal point value in Amount field highlight field label in red color.

Expected Result : If decimal point value is accepted then Amount field should not be highlighted in red color.

![ps-10](https://user-images.githubusercontent.com/31267260/30237358-d45a6c66-954d-11e7-918e-fed5018f0303.jpg)

**Comment by prashantk0270** [comment]
done & updated

**Comment by bhavinshah09** [comment]
The issue is Fixed and verified.
