### ISSUE TITLE
[Member Dashboard]: Main image drops down upon clicking randomly on the image.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#92]
Actual Result : Main image drops down upon clicking randomly on the image.

Expected Result : Main image should not drop down upon clicking randomly on the image. If it is a part of some animation then change it as it does not appear properly.

Steps to Reproduce : 

1. Go to http://52.163.113.185:3001/#/login
2. Login using Member username and password
3. Scroll down until Trending Holidays.
4. Click on the main image randomly 4-5 times
5. Click up and below the image.
6. Repeat steps 4-5 until the image drops down.

![dash-01](https://user-images.githubusercontent.com/31267260/30239514-e2f43328-957b-11e7-87a7-4500841f8e06.jpg)

Ref Img

![dash-01](https://user-images.githubusercontent.com/31267260/30239249-eb1d2c72-9575-11e7-932f-df55851b6892.jpg)

**Comment by prashantk0270** [comment]
done & updated

**Comment by bhavinshah09** [comment]
The issue is Fixed and verified. Trending Holidays section is removed.
