### ISSUE TITLE
[Role]: Accessing the role using image, view and edit icon redirects to a different page.***

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#93]
Actual Result : Accessing the role using image, view and edit icon redirects to a different page.

Expected Result : Accessing the role using image, view and edit icon should redirect the user to record permission page.

![rol-02](https://user-images.githubusercontent.com/31267260/30240001-8e8c1c56-9585-11e7-94f8-a12e9de73a1a.jpg)

**Comment by jariwbh** [comment]
done

**Comment by bhavinshah09** [comment]
The issue is Fixed and verified.
