### ISSUE TITLE
[Role]: Revise the labels to Personal Information, Work Details and Family Member Details.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#96]
Revise the labels to Personal Information, Work Details and Family Member Details.

Note : Revise the labels for both tabs Role Permission and Field Permission

![rol-04](https://user-images.githubusercontent.com/31267260/30258068-d70ffda4-96d3-11e7-8de8-c277e643e497.jpg)

**Comment by jariwbh** [comment]
done

**Comment by bhavinshah09** [comment]
The issue is Fixed and verified.
