### ISSUE TITLE
[Role]: Typo in Field Permission tab, spelling of Information is incorrect.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#98]
Actual Result : Incorrect spelling of Information.

Expected Result  : Correct the spelling of Information and revise the label to Basic Information.

Steps to Reproduce : 

1. Go to http://52.163.113.185:3001/#/login
2. Login using admin username and password
3. Navigate to Role page under Users and Role
4. Navigate to Field Permission tab.
5. Change Form Name to admin
-> Observe the issue.

![rol-06](https://user-images.githubusercontent.com/31267260/30258504-b6a62cce-96d7-11e7-991e-a8bfc98c25d1.jpg)

**Comment by jariwbh** [comment]
done

**Comment by bhavinshah09** [comment]
The issue is Fixed and verified.
