### ISSUE TITLE
[Role]: Typo in Field Permission tab, spelling of Business and Designation is incorrect in Work Detail.

### ISSUE THREAD

**Issue by bhavinshah09** [jariwbh/Timesvecanza-Portal#99]
Actual Result : Typo in Field Permission tab, spelling of Business and Designation is incorrect in Work Detail.

Expected Result : Correct the spelling of Business and Designation is incorrect in Work Detail.

![rol-07](https://user-images.githubusercontent.com/31267260/30258812-3e66df3a-96da-11e7-8459-5b948dcc38d0.jpg)

**Comment by jariwbh** [comment]
done

**Comment by bhavinshah09** [comment]
The issue is Fixed and verified.
